language: python
sudo: true
python:
  - "2.6"
  - "2.7"
 # command to install dependencies
install:
    - git clone https://github.com/ldtp/ldtp2.git
    - cd ldtp2/
    - sudo python setup.py install
    - cd ../
    - pip install -r requirements.txt
    - pip install -e .
# before
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
# run
script: echo "pass"
branches:
    only:
    - master
